[package]
name = "rand_map"
version = "0.0.5"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
hashers = "*"
rand = "*"
serde = { version = "*", features = ["derive"], optional = true }

[features]
serialize = ["serde"]
